#include <iostream>
#include <algorithm>
#include <utility>

map<pair<string,string>, string> tabela;

tabela[{"PROGRAMA", "PROGRAMAINICIO"}] = "PROGRAMAINICIO D EXECUCAOINICIO COMANDO FIMEXECUCAO FIMPROGRAMA";

tabela[{"DECLARACAO", "DEFINAINSTRUCAO"}]="DEFINAINSTRUCAO IDENTIFICADOR COMO COMANDO";

tabela[{"DECLARACAO'", "DEFINAINSTRUCAO"}]="DECLARACAO DECLARACAO'";

tabela[{"COMANDO","LAMPADA APAGADA A DIREITA"}]="INSTRUCAO";
tabela[{"COMANDO","LAMPADA ACESA A DIREITA"}]="INSTRUCAO";
tabela[{"COMANDO","LAMPADA APAGADA A ESQUERDA"}]="INSTRUCAO";
tabela[{"COMANDO","LAMPADA ACESSA A ESQUERDA"}]="INSTRUCAO";
tabela[{"COMANDO","LAMPADA APAGADA A FRENTE"}]="INSTRUCAO";
tabela[{"COMANDO","LAMPADA ACESA A FRENTE"}]="INSTRUCAO";
tabela[{"COMANDO","ESQUERDA ROBO BLOQUEADA"}]="INSTRUCAO";
tabela[{"COMANDO","DIREITA ROBO BLOQUEADA"}]="INSTRUCAO";
tabela[{"COMANDO","FRENTE ROBO BLOQUEADA"}]="INSTRUCAO";
tabela[{"COMANDO","ROBO MOVIMENTANDO"}]="INSTRUCAO";
tabela[{"COMANDO","ROBO PARADO"}]="INSTRUCAO";
tabela[{"COMANDO","ROBO OCUPADO"}]="INSTRUCAO";
tabela[{"COMANDO","ROBO PRONTO"}]="INSTRUCAO";
tabela[{"COMANDO","AGUARDE ATE"}]="INSTRUCAO";
tabela[{"COMANDO","ACENDA LAMPADA"}]="INSTRUCAO";
tabela[{"COMANDO","APAGUE LAMPADA"}]="INSTRUCAO";
tabela[{"COMANDO","FINALIZE"}]="INSTRUCAO";
tabela[{"COMANDO","PARE"}]="INSTRUCAO";
tabela[{"COMANDO","IDENTIFICADOR"}]="INSTRUCAO";
tabela[{"COMANDO","VIRE PARA"}]="INSTRUCAO";
tabela[{"COMANDO","MOVA"}]="INSTRUCAO";
tabela[{"COMANDO","SE"}]="CONDICIONAL";
tabela[{"COMANDO","EQUANTO"}]="LACO";
tabela[{"COMANDO","REPITA"}]="ITERACAO";
tabela[{"COMANDO","INICIO"}]="BLOCO";

tabela[{"COMANDO'","LAMPADA APAGADA A DIREITA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","LAMPADA ACESA A DIREITA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","LAMPADA APAGADA A ESQUERDA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","LAMPADA ACESSA A ESQUERDA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","LAMPADA APAGADA A FRENTE"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","LAMPADA ACESA A FRENTE"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","ESQUERDA ROBO BLOQUEADA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","DIREITA ROBO BLOQUEADA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","FRENTE ROBO BLOQUEADA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","ROBO MOVIMENTANDO"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","ROBO PARADO"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","ROBO OCUPADO"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","ROBO PRONTO"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","AGUARDE ATE"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","ACENDA LAMPADA"}]="COMANDO COMANDO' ";
tabela[{"COMANDO'","APAGUE LAMPADA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","FINALIZE"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","PARE"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","IDENTIFICADOR"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","VIRE PARA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","MOVA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","SE"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","EQUANTO"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","REPITA"}]="COMANDO COMANDO'";
tabela[{"COMANDO'","FIM"}]="&";
tabela[{"COMANDO'","INICIO"}]="COMANDO COMANDO'";

tabela[{"BLOCO","INICIO"}]="INICIO COMANDO' FIM";

tabela[{"ITERACAO","REPITA"}]="REPITA NUMERO VEZES' COMANDO FIMREPITA";

tabela[{"VEZES'","VEZES"}]="VEZES";
tabela[{"VEZES'","VEZES"}]="VEZ";

tabela[{"LACO","ENQUANTO"}]="ENQUANTO CONDICAO FACA COMANDO FIMPARA";

tabela[{"CONDICIONAL","SE"}]="SE CONDICAO ENTAO COMANDO FIMSE ELSE";

tabela[{"SENAO'","SENAO"}]="SENAO COMANDO FIMSENAO";

tabela[{"INSTRUCAO","LAMPADA APAGADA A DIREITA"}]="CONDICAO";
tabela[{"INSTRUCAO","LAMPADA ACESA A DIREITA"}]="CONDICAO";
tabela[{"INSTRUCAO","LAMPADA APAGADA A ESQUERDA"}]="CONDICAO";
tabela[{"INSTRUCAO","LAMPADA ACESSA A ESQUERDA"}]="CONDICAO";
tabela[{"INSTRUCAO","LAMPADA APAGADA A FRENTE"}]="CONDICAO";
tabela[{"INSTRUCAO","LAMPADA ACESA A FRENTE"}]="CONDICAO";
tabela[{"INSTRUCAO","ESQUERDA ROBO BLOQUEADA"}]="CONDICAO";
tabela[{"INSTRUCAO","DIREITA ROBO BLOQUEADA"}]="CONDICAO";
tabela[{"INSTRUCAO","FRENTE ROBO BLOQUEADA"}]="CONDICAO";
tabela[{"INSTRUCAO","ROBO MOVIMENTANDO"}]="CONDICAO";
tabela[{"INSTRUCAO","ROBO PARADO"}]="CONDICAO";
tabela[{"INSTRUCAO","ROBO OCUPADO"}]="CONDICAO";
tabela[{"INSTRUCAO","ROBO PRONTO"}]="CONDICAO";
tabela[{"INSTRUCAO","AGUARDE ATE"}]="AGUARDE ATE";
tabela[{"INSTRUCAO","ACENDA LAMPADA"}]="ACENDA LAMPADA";
tabela[{"INSTRUCAO","APAGUE LAMPADA"}]="APAGUE LAMPADA";
tabela[{"INSTRUCAO","FINALIZE"}]="FINALIZE";
tabela[{"INSTRUCAO","PARE"}]="PARE";
tabela[{"INSTRUCAO","IDENTIFICADOR"}]="IDENTIFICADOR";
tabela[{"INSTRUCAO","VIRE PARA"}]="VIRE PARA SENTIDO";
tabela[{"INSTRUCAO","MOVA"}]="MOVA NUMERO PASSOS";

tabela[{"PASSOS'","PASSOS"}]="PASSOS";
tabela[{"PASSOS'","PASSO"}]="PASSO";

tabela[{"CONDICAO","LAMPADA APAGADA A DIREITA"}]="LAMPADA APAGADA A DIREITA";
tabela[{"CONDICAO","LAMPADA ACESA A DIREITA"}]="LAMPADA ACESA A DIREITA";
tabela[{"CONDICAO","LAMPADA APAGADA A ESQUERDA"}]="LAMPADA APAGADA A ESQUERDA";
tabela[{"CONDICAO","LAMPADA ACESSA A ESQUERDA"}]="LAMPADA ACESSA A ESQUERDA";
tabela[{"CONDICAO","LAMPADA APAGADA A FRENTE"}]="LAMPADA APAGADA A FRENTE";
tabela[{"CONDICAO","LAMPADA ACESA A FRENTE"}]="LAMPADA ACESA A FRENTE";
tabela[{"CONDICAO","ESQUERDA ROBO BLOQUEADA"}]="ESQUERDA ROBO BLOQUEADA";
tabela[{"CONDICAO","DIREITA ROBO BLOQUEADA"}]="DIREITA ROBO BLOQUEADA";
tabela[{"CONDICAO","FRENTE ROBO BLOQUEADA"}]="FRENTE ROBO BLOQUEADA";
tabela[{"CONDICAO","ROBO MOVIMENTANDO"}]="ROBO MOVIMENTANDO";
tabela[{"CONDICAO","ROBO PARADO"}]="ROBO PARADO";
tabela[{"CONDICAO","ROBO OCUPADO"}]="ROBO OCUPADO";
tabela[{"CONDICAO","ROBO PRONTO"}]="ROBO PRONTO";

tabela[{"SENTIDO","DIREITA"}]="DIREITA";
tabela[{"SENTIDO","ESQUERDA"}]="ESQUERDA";
